# Automatically generated by configure - do not modify
SRC_PATH=/home/hari/Desktop/project/faros/faros/panda/qemu/roms/vgabios
CC=gcc
CXX=g++
LINKER=g++
BCC=bcc
CPP=cpp
OBJCOPY=objcopy
IASL=iasl
LD=ld
